### ISSUE TITLE
Another way to install without using Docker

### ISSUE THREAD

**Issue by alissonash** [instructure/rollcall-attendance#91]
**Roll Call can be run locally on your machine**..

What is this other way of installing? I don't use Canvas LMS in Docker.

I appreciate if you can share another installation method on a server (Debian / Ubuntu)

**Comment by ktgeek** [comment]
I dug back into our code repository to find non-docker instructions.  These are unsupported, but have enough of the steps to get you where you need to go:

Production setup
----------------

### Configuration

#### Database

1. Create a Postgres database for the app
2. cp config/database.yml.sample config/database.yml and edit as needed

#### Redis

1. Set up a Redis installation
2. cp config/redis.yml.sample config/redis.yml and edit as needed

#### LTI

1. cp config/lti.yml.sample config/lti.yml and edit as needed

#### Canvas API

1. Acquire a cloud Canvas Devloper API key.
    When requesting a developer key, the redirect_uri is the same as the root URL (e.g. https://attendance.instructure.com).
2. cp config/canvas.yml.sample config/canvas.yml and edit as needed

#### Resque

1. In order to process reports, Resque must be running in the background:

    RAILS_ENV=production QUEUE=* bundle exec rake resque:work

2. cp config/resque.yml.sample config/resque.yml and set the username and password for accessing Resque's admin panel at /resque

### Initial setup

    bundle install
    bundle exec rake db:setup

If all is well, when you start the server you should see output resembling the following:

    Initializing Canvas using configuration in canvas.yml
    Initializing LTI key and secret using configuration in lti.yml
    Initializing Redis server at redis://localhost:6379

LTI setup
--------------
Visit [your_host]/configure.xml to get the LTI xml configuration
